For some reason the MacOSX classload works on Linux, but then fails on the actual class usage with a NoClassDefFoundError. Changed to catch Throwable for the MacOSX-specific section.